name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-unit-tests:
    name: Build and Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Debug and run unit tests
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:testDebugUnitTest

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            app/build/test-results/testDebugUnitTest/**
            app/build/reports/tests/testDebugUnitTest/**

  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run lint
        run: ./gradlew --no-daemon --stacktrace :app:lintDebug

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

  # NOTE: Instrumentation tests are temporarily disabled. Rationale:
  # - Linux GitHub-hosted runners are currently unreliable for this project's emulator
  #   (graphics/virtualization constraints lead to emulator boot failures/timeouts).
  # - macOS runners work more reliably with the Android emulator but are costly in Actions minutes,
  #   which isn't viable for this public repo.
  # - A self-hosted runner isn't available at the moment.
  # To re-enable later, remove the `if: ${{ false }}` line below (or gate on a repo variable).
  instrumentation-tests:
    if: ${{ false }}
    name: Instrumentation Tests (Emulator)
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache AVD
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/avd
            ~/.android/adb
          key: avd-${{ runner.os }}-api30-google_apis-x86_64-v1
          restore-keys: |
            avd-${{ runner.os }}-

      - name: Pre-build app and androidTest APKs
        run: ./gradlew --no-daemon --stacktrace :app:assembleDebug :app:assembleAndroidTest

      - name: Run emulator and connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: google_apis
          profile: pixel_6
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -no-boot-anim -camera-back none -noaudio
          disable-animations: false
          script: ./gradlew --no-daemon --stacktrace :app:connectedDebugAndroidTest

      - name: Upload androidTest reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-reports
          path: |
            app/build/outputs/androidTest-results/**
            app/build/reports/androidTests/connected/**
