name: Nightly Trunk Upgrade

on:
  schedule:
    - cron: 0 8 * * 1-5 # 8 AM UTC Mon-Fri
  workflow_dispatch: {}

permissions: read-all

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade Trunk & Create PR
        uses: trunk-io/trunk-action/upgrade@v1
